# Assignment 3


- Student Name: Karina Jonina
- Student ID: c00278440

- Module Name: Programming for Data Scientists
- Module Code: PROGC5201
- Module Leader: Paul Barry

- Course Name: 		Master of Science in Data Science
- Course Code:		 CW_KCDAR_M Y5

- Due Date: 10th January 2022 9:00am

In [2]:
import pandas as pd
import datetime
from os import listdir
from os.path import isfile, join
import glob
import re
from datetime import datetime

In [3]:
# gettting the CSV from the website
url = 'https://opendata-geohive.hub.arcgis.com/datasets/d8eb52d56273413b84b0187a4e9117be_0.csv?outSR=%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D.'
# url = 'COVID-19.csv'
df = pd.read_csv(url)


In [4]:
# Ensuring the Date is just date, and not datetime
df['Date'] = pd.to_datetime(df['Date']).dt.date
df.head()

X          Y        Date  ConfirmedCovidCases  \
0 -7.692596  53.288234  2020-02-29                    1   
1 -7.692596  53.288234  2020-03-03                    1   
2 -7.692596  53.288234  2020-03-04                    4   
3 -7.692596  53.288234  2020-03-05                    7   
4 -7.692596  53.288234  2020-03-06                    5   

   TotalConfirmedCovidCases  ConfirmedCovidDeaths  TotalCovidDeaths  \
0                         1                   0.0                 0   
1                         2                   0.0                 0   
2                         6                   0.0                 0   
3                        13                   0.0                 0   
4                        18                   0.0                 0   

    StatisticsProfileDate  CovidCasesConfirmed  HospitalisedCovidCases  ...  \
0  2020/02/27 00:00:00+00                  NaN                     NaN  ...   
1  2020/03/01 00:00:00+00                  NaN                     NaN  ...   
2  2020/03/02 00:00:00+00                  1.0                     0.0  ...   
3  2020/03/03 00:00:00+00                  2.0                     1.0  ...   
4  2020/03/04 00:00:00+00                  5.0                     4.0  ...   

   CommunityTransmission  CloseContact  TravelAbroad  FID  \
0                      0             0             0    1   
1                      0             0             0    2   
2                      0             0             0    3   
3                      0             0             0    4   
4                      0             0             0    5   

   HospitalisedAged65to74  HospitalisedAged75to84  HospitalisedAged85up  \
0                     NaN                     NaN                   NaN   
1                     NaN                     NaN                   NaN   
2                     0.0                     0.0                   0.0   
3                     0.0                     0.0                   0.0   
4                     0.0                     0.0                   0.0   

   Aged65to74  Aged75to84  Aged85up  
0         NaN         NaN       NaN  
1         NaN         NaN       NaN  
2         0.0         0.0       0.0  
3         0.0         0.0       0.0  
4         0.0         0.0       0.0  

[5 rows x 41 columns]

In [5]:
# examining columns and rows
df.shape

(648, 41)

In [6]:
# checking type for each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 648 entries, 0 to 647
Data columns (total 41 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   X                            648 non-null    float64
 1   Y                            648 non-null    float64
 2   Date                         648 non-null    object 
 3   ConfirmedCovidCases          648 non-null    int64  
 4   TotalConfirmedCovidCases     648 non-null    int64  
 5   ConfirmedCovidDeaths         499 non-null    float64
 6   TotalCovidDeaths             648 non-null    int64  
 7   StatisticsProfileDate        648 non-null    object 
 8   CovidCasesConfirmed          646 non-null    float64
 9   HospitalisedCovidCases       646 non-null    float64
 10  RequiringICUCovidCases       646 non-null    float64
 11  HealthcareWorkersCovidCases  646 non-null    float64
 12  ClustersNotified             626 non-null    float64
 13  HospitalisedAged5   

In [7]:
# examining the names of the columns
df.columns

Index(['X', 'Y', 'Date', 'ConfirmedCovidCases', 'TotalConfirmedCovidCases',
       'ConfirmedCovidDeaths', 'TotalCovidDeaths', 'StatisticsProfileDate',
       'CovidCasesConfirmed', 'HospitalisedCovidCases',
       'RequiringICUCovidCases', 'HealthcareWorkersCovidCases',
       'ClustersNotified', 'HospitalisedAged5', 'HospitalisedAged5to14',
       'HospitalisedAged15to24', 'HospitalisedAged25to34',
       'HospitalisedAged35to44', 'HospitalisedAged45to54',
       'HospitalisedAged55to64', 'Male', 'Female', 'Unknown', 'Aged1to4',
       'Aged5to14', 'Aged15to24', 'Aged25to34', 'Aged35to44', 'Aged45to54',
       'Aged55to64', 'Median_Age', 'CommunityTransmission', 'CloseContact',
       'TravelAbroad', 'FID', 'HospitalisedAged65to74',
       'HospitalisedAged75to84', 'HospitalisedAged85up', 'Aged65to74',
       'Aged75to84', 'Aged85up'],
      dtype='object')

## Examining location
Below exploration showed that there are no unique locations in the dataset and therefore, redundant. 

In [8]:
df['X'].unique()

array([-7.692596])

In [9]:
df['Y'].unique()

array([53.288234])

In [10]:
df['CommunityTransmission'].unique()

array([0], dtype=int64)

In [11]:
df['CloseContact'].unique()

array([0], dtype=int64)

In [12]:
df['TravelAbroad'].unique()

array([0], dtype=int64)

### Dropping Columns (X and Y)

| Column | Reason |
|---|---|
| df['X'] | no unique values |
| df['Y'] | no unique values |
| df['StatisticsProfileDate'] | Very similar to df['Date']|
| df['CovidCasesConfirmed'] | Very similar to df['Total Confirmed Covid Cases'] |
| df['FID'] | very similar to Index in pandas |
| df['CommunityTransmission'] | no unique values |
| df['CloseContact'] | no unique values |
| df['TravelAbroad'] | no unique values |


In [13]:
# Dropping irrelevant columns
df = df.drop(columns = ['X','Y','CovidCasesConfirmed','StatisticsProfileDate', 'FID', 
                        'CommunityTransmission', 'CloseContact','TravelAbroad'])

## Examining date
Below exploration showed that there are are unique dates in the dataset. 

In [14]:
df['Date'].unique()

array([datetime.date(2020, 2, 29), datetime.date(2020, 3, 3),
       datetime.date(2020, 3, 4), datetime.date(2020, 3, 5),
       datetime.date(2020, 3, 6), datetime.date(2020, 3, 7),
       datetime.date(2020, 3, 8), datetime.date(2020, 3, 9),
       datetime.date(2020, 3, 10), datetime.date(2020, 3, 11),
       datetime.date(2020, 3, 12), datetime.date(2020, 3, 13),
       datetime.date(2020, 3, 14), datetime.date(2020, 3, 15),
       datetime.date(2020, 3, 16), datetime.date(2020, 3, 17),
       datetime.date(2020, 3, 18), datetime.date(2020, 3, 19),
       datetime.date(2020, 3, 20), datetime.date(2020, 3, 21),
       datetime.date(2020, 3, 22), datetime.date(2020, 3, 23),
       datetime.date(2020, 3, 24), datetime.date(2020, 3, 25),
       datetime.date(2020, 3, 26), datetime.date(2020, 3, 27),
       datetime.date(2020, 3, 28), datetime.date(2020, 3, 29),
       datetime.date(2020, 3, 30), datetime.date(2020, 3, 31),
       datetime.date(2020, 4, 1), datetime.date(2020, 4, 2),
 

## Melting 

In [15]:
# Melting
id_vars = ["Date"]

df = pd.melt(frame=df,id_vars=id_vars, var_name="Column", value_name="Cases")

df.head(10)


Date               Column  Cases
0  2020-02-29  ConfirmedCovidCases    1.0
1  2020-03-03  ConfirmedCovidCases    1.0
2  2020-03-04  ConfirmedCovidCases    4.0
3  2020-03-05  ConfirmedCovidCases    7.0
4  2020-03-06  ConfirmedCovidCases    5.0
5  2020-03-07  ConfirmedCovidCases    1.0
6  2020-03-08  ConfirmedCovidCases    2.0
7  2020-03-09  ConfirmedCovidCases    3.0
8  2020-03-10  ConfirmedCovidCases   10.0
9  2020-03-11  ConfirmedCovidCases    9.0

# Getting the final dataset

In [16]:
df.head()

Date               Column  Cases
0  2020-02-29  ConfirmedCovidCases    1.0
1  2020-03-03  ConfirmedCovidCases    1.0
2  2020-03-04  ConfirmedCovidCases    4.0
3  2020-03-05  ConfirmedCovidCases    7.0
4  2020-03-06  ConfirmedCovidCases    5.0

In [17]:
df['Age_Range'] = df['Column']
df.tail()

Date    Column   Cases Age_Range
20731  2021-12-05  Aged85up  9786.0  Aged85up
20732  2021-12-06  Aged85up  9797.0  Aged85up
20733  2021-12-07  Aged85up  9808.0  Aged85up
20734  2021-12-08  Aged85up  9826.0  Aged85up
20735  2021-12-09  Aged85up  9834.0  Aged85up

In [18]:
df['Age_Range'] = df['Age_Range'].str.replace('to','-')

In [19]:
df['Age_Range']= df['Age_Range'].str.replace('up','+')

In [20]:
df['Age_Range']

0        ConfirmedCovidCases
1        ConfirmedCovidCases
2        ConfirmedCovidCases
3        ConfirmedCovidCases
4        ConfirmedCovidCases
                ...         
20731                Aged85+
20732                Aged85+
20733                Aged85+
20734                Aged85+
20735                Aged85+
Name: Age_Range, Length: 20736, dtype: object

In [21]:
import numpy as np
df['Age_Range']= df['Age_Range'].replace("TotalConfirmedCovidCases", np.nan)
df['Age_Range']= df['Age_Range'].replace("ConfirmedCovidCases",np.nan)
df['Age_Range']= df['Age_Range'].replace("TotalCovidDeaths", np.nan)
df['Age_Range']= df['Age_Range'].replace("ConfirmedCovidDeaths",np.nan)
df['Age_Range']= df['Age_Range'].replace("HospitalisedCovidCases", np.nan)
df['Age_Range']= df['Age_Range'].replace("RequiringICUCovidCases", np.nan)
df['Age_Range']= df['Age_Range'].replace("HealthcareWorkersCovidCases", np.nan)
df['Age_Range']= df['Age_Range'].replace("ClustersNotified", np.nan)
df['Age_Range']= df['Age_Range'].str.replace("Aged", '')

df['Age_Range']= df['Age_Range'].str.replace("Hospitalised5", '1-4')
df['Age_Range']= df['Age_Range'].str.replace("Hospitalised", '')
df['Age_Range']= df['Age_Range'].replace("Median_Age", np.nan)
df['Age_Range']= df['Age_Range'].replace("Male", np.nan)
df['Age_Range']= df['Age_Range'].replace("Female", np.nan)
df['Age_Range']= df['Age_Range'].replace("Female", np.nan)

df['Age_Range']= df['Age_Range'].replace("Unknown",np.nan)

In [22]:
df["Age_Range"].unique()

array([nan, '1-4', '1-4-14', '15-24', '25-34', '35-44', '45-54',
       '1-45-64', '5-14', '55-64', '65-74', '75-84', '85+'], dtype=object)

In [ ]:
df.head()

In [ ]:
df = df [[
    "Date",
    "Column",
    "Age_Range",
    "Cases"
]]

In [ ]:
df.head()

In [ ]:
# checking that 'HospitalisedAged5' with have 5
df[df["Column"] =='HospitalisedAged5'].head()

In [ ]:
# checking that 'HospitalisedAged85up' with have 85
df[df["Column"] =='HospitalisedAged85up'].head()

### Dropping rows with NaN in cases

In [ ]:
df.head(20)

In [ ]:
df = df[~df['Cases'].isna()]
df["Cases"] = df["Cases"].astype(int)
# reseting the dataframe index
df = df.reset_index(drop = True)

In [ ]:
df.head()

In [ ]:
df.shape

### Dealing with ['Column'] column

In [ ]:
# Testing the regular expression
line = 'HospitalisedAged45to54'
match = re.findall('([A-Z][a-z]+)', line)
new_line = match[0] + " " + match[1] 
print(new_line)

In [ ]:
column_list = []
for i in  df["Column"]:
    match = re.findall('([A-Z][a-z]+)', i)
    if len(match) == 4:
        new_line = match[0] + ' ' + match[1] + ' ' + match[2] + ' ' + match[3]
    elif len(match) == 3:
        new_line = match[0] + ' ' + match[1] + ' ' + match[2]
    elif len(match) == 2:
        new_line = match[0] + ' ' + match[1] 
    else:
        new_line = match[0]

    column_list.append(new_line)

# examining the list
print(column_list)  

In [ ]:
column_list = pd.Series(column_list)
column_list = column_list.reset_index()

In [ ]:
df = pd.merge(df, column_list, left_index = True, right_index = True)

In [ ]:
df = df.rename(columns={'Column': "old_column", 0 : "Column"})

In [ ]:
df = df[[
    "Date",
    "old_column",
    "Column",
    "Age_Range",
    "Cases"
]]

In [ ]:
df.head()

### Daily Cases

In [ ]:
hospitalised_df = df[df['Column'].str.contains("Hospitalised Aged")]
age_range_65up = hospitalised_df[hospitalised_df['Age_Range'] == '65-74']
age_range_65up.tail(10)

In [ ]:
aged_df = df[df['Column'].str.startswith("Aged")]
aged_df.tail(50)

In [ ]:
age_list = ['0-4' '5-14' '15-24' '25-34' '35-44' '45-54' '55-64', '1-4' '65-74', '75-84' '85+']

# removing NaN from the dataset
age_list = age_list[1:]
print(age_list)

### Columns that are Not Accumulated
'Confirmed Covid Cases', 'Total Confirmed Covid Cases','Confirmed Covid Deaths', 'Total Covid Deaths',

In [ ]:
df['Column'].unique()

In [ ]:
column_list = ['Confirmed Covid Cases', 'Total Confirmed Covid Cases',
       'Confirmed Covid Deaths', 'Total Covid Deaths',
       'Hospitalised Covid Cases', 'Requiring Covid Cases',
       'Healthcare Workers Covid Cases', 'Clusters Notified',
       'Hospitalised Aged', 'Male', 'Female', 'Unknown', 'Aged',
       'Median Age']
column_list

In [ ]:
# Columns that have accumulated cases and no daily cases count 
accumulated = ['Male','Hospitalised Covid Cases', 'Hospitalised Aged', 
               'Healthcare Workers Covid Cases', 'Aged', 'Unknown', 'Female',
               'Median Age', 'Requiring Covid Cases', 'Clusters Notified']

In [ ]:
df1_list = []
df1 = pd.DataFrame()
for i in column_list:
    if "Hospitalised Aged" == i: 
        for age in age_list:
            df1 = hospitalised_df[hospitalised_df['Age_Range'].str.contains(age)]
            df1 = pd.DataFrame(df1)
            df1['Daily Cases'] = df1['Cases'].diff(1)
            df1 = df1.dropna()
            df1["Daily Cases"] = df1["Daily Cases"].astype(int)
            df1_list.append(df1)
        
    elif "Aged" == i: 
        for age in age_list:
            df1 = aged_df[aged_df['Age_Range'].str.contains(age)]
            df1 = pd.DataFrame(df1)
            df1['Daily Cases'] = df1['Cases'].diff(1)
            df1 = df1.dropna()
            df1["Daily Cases"] = df1["Daily Cases"].astype(int)
            df1_list.append(df1)
    
    elif  i in accumulated:
        df1 = df[df['Column'].str.contains(i)]
        df1 = pd.DataFrame(df1)
        df1['Daily Cases'] = df1['Cases'].diff(1)
#         df1 = df1.dropna()
#         df1["Daily Cases"] = df1["Daily Cases"].astype(int)
        df1_list.append(df1)
    else:
        df1 = df[df['Column'].str.contains(i)]
        df1 = pd.DataFrame(df1)
        df1['Daily Cases'] = 'NaN'
#         df1 = df1.dropna()
#         df1["Daily Cases"] = df1["Daily Cases"].astype(int)
        df1_list.append(df1) 

In [ ]:
new_df =  pd.concat(df1_list)
# sorting data by date
new_df = new_df.sort_values(ascending = True, by = ["Date"])

# reseting the dataframe index
new_df = new_df.reset_index(drop=True)
new_df.head(50)

In [ ]:
df.head(50)

In [ ]:
df.tail(50)

### Saving to a new csv file

In [ ]:
new_df.to_csv(r"tidy_data_df.csv", index =  False)